theme = "sonokai"

[editor]
line-number = "absolute"
mouse = false
rulers = [100]
true-color = true
cursorline = true
color-modes = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
character = "╎"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
"C-x" = [":sh cargo run"]
"C-A-x" = [":sh cargo test"]
"D" = ["extend_to_line_bounds", "delete_selection"]
"q" = "no_op"
"Q" = "no_op"

[keys.select]
"D" = ["extend_to_line_bounds", "delete_selection"]

[keys.insert]
"left" = "move_char_left"
"right" = "move_char_right"
# "down" = "move_line_down"
# "up" = "move_line_up"
