theme = "sonokai"

[editor]
line-number = "absolute"
mouse = false
rulers = [100]
true-color = true
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
character = "╎"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
"C-x" = [":sh cargo run"]
"C-A-x" = [":sh cargo run --release"]
"D" = ["extend_to_line_bounds", "delete_selection"]
"q" = "no_op"
"Q" = "no_op"

[keys.select]
"D" = ["extend_to_line_bounds", "delete_selection"]