theme = "sonokai"

[editor]
line-number = "absolute"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[keys.normal]
"C-x" = [":sh cargo run"]
"C-A-x" = [":sh cargo run --release"]