[[language]]
name = "rust"
# language-servers = {checkonsave = true, command = "clippy", args = ["--all-features"]}

[language-server.rust-analyzer.config.check]
command = "clippy"
extraArgs = ["--all-features"] 
